config/routes.rb
Jackpot::Engine.routes.draw do

  resources :customers  do
    member do
      put "credit_card" 
    end 
  end 

  resources :subscriptions 
  resources :payments 

  match "/payments/:payment_id/receipt" => "receipts#show",                      :as => 'receipt_payment'
  match "/payments/:payment_id/receipt/:public_token" => "receipts#public_show", :as => 'public_receipt_payment'

  root :to => "payments#index"
  devise_for :users, {
    :class_name => 'Jackpot::User',
    :module     => :devise
  }
end

app/models/jackpot/card.rb
module Jackpot

  # A simple decorator to Active Merchant's Card.
  #
  class Card
    def initialize(card_hash)
      @component  = ActiveMerchant::Billing::CreditCard.new(HashWithIndifferentAccess.new(card_hash))
    end

    def type
      @component.brand
    end

    def method_missing(meth, *args)
      if @component.respond_to?(meth)
        @component.send(meth, *args)
      else
        super
      end
    end

    def respond_to?(meth)
      unless @component.respond_to?(meth)
        super.respond_to? meth
      end
    end

    def masquerade_number
      "XXXX-XXXX-XXXX-#{number.last(4)}"
    end

  end
end

app/models/jackpot/customer.rb
module Jackpot
  class Customer < ActiveRecord::Base
    belongs_to      :subscription
    has_many        :payments, :through => :subscription  

    attr_protected  :credit_card_number
    attr_protected  :credit_card_expiry_year
    attr_protected  :credit_card_expiry_month
    attr_protected  :credit_card_token

    
    scope :due_in , lambda { |number_of_days| where("good_until <= ?", 
                                                    number_of_days.days.from_now) }

    # Returns customers that are overdue
    scope :overdue , lambda { due_in(-1) }

    # Returns every customer that has a card about to expire within the given period composed 
    # of today plus a number of months. Defaults to 3 months 
    #
    # number_of_months -> number of months from now. Default: 3  
    scope :with_expiring_card , lambda { |number_of_months=3| 
      cut_date = (Date.today + number_of_months.months).at_beginning_of_month
      where("credit_card_expiry_month <= ? AND credit_card_expiry_year <= ?", 
            cut_date.month, cut_date.year) 
    } 
    

    # Returns every customer with already expired cards 
    scope :with_expired_card, lambda { with_expiring_card(-1) }




    attr_accessor   :credit_card_verification_value

    def pay_subscription
      if credit_card_token   
        if subscription.present? && subscription.charge(self)
          update_attribute(:good_until, Date.today + 1.month)
        end 
      else 
        raise Jackpot::Errors::CustomerHasNoCardSaved.new
      end 
    end 
    

    def update_credit_card(card)  
      raise Errors::CardIsInvalid unless card.valid? 
      write_attribute  :credit_card_number            ,  card.masquerade_number
      write_attribute  :credit_card_expiry_month      ,  card.month
      write_attribute  :credit_card_expiry_year       ,  card.year

      # This should never be recorded 
      self.credit_card_verification_value = card.verification_value
      stored_card_response = Jackpot::Base.gateway.store(card)
      write_attribute :credit_card_token , stored_card_response.params["customer_vault_id"]

      save
    end 

    def expiration_date
      "#{credit_card_expiry_month}/#{credit_card_expiry_year}"
    end 


    # Checks if this customer's card will expire within the next :months. 
    # 
    # number_of_months -> Number of months within this card will expire. Defaults to 3 
    def expiring?(number_of_months=3)
      (Date.parse(expiration_date) - number_of_months.months) <= Date.today.at_beginning_of_month
    end 

  end
end

app/models/jackpot/gateway.rb
module Jackpot 

  # Small adapter for Active Merchant gateways Jackpot supports
  class Gateway

    def initialize(adapted_gateway)
      @adapted_gateway = adapted_gateway
    end 


    def authorize(amount_in_cents, credit_card_token) 
      @adapted_gateway.authorize(amount_in_cents, credit_card_token)
    end 

    def store(card)
      @adapted_gateway.store(card)
    end 

    def capture(money, authorization, options = {})
      @adapted_gateway.capture(money, authorization, options) 
    end 

    def process_payment(credit_card_token, amount_in_cents)
      if credit_card_token
        response = Jackpot::Base.gateway.authorize(amount_in_cents, credit_card_token)

        if response.success?
          billing_response = Jackpot::Base.gateway.capture(amount_in_cents, response.authorization).authorization
        else
          raise Jackpot::Errors::UnauthorizedPayment.new
        end
      else
        raise Jackpot::Errors::CustomerHasNoCardSaved.new
      end 
    end

  end 
end 

app/models/jackpot/payment.rb
module Jackpot
  class Payment < ActiveRecord::Base
    before_create :perform_payment
    before_create :assign_public_token
    after_create  :send_receipt

    attr_accessor :credit_card
    attr_accessor :credit_card_token

    belongs_to :subscription
    belongs_to :customer

    def self.public_fetch(payment_id, params)
      find_by_id_and_public_token! payment_id , params[:public_token]
    end 

    def perform_payment
      self.payment_transaction_token = Jackpot::Base.gateway.process_payment(customer.credit_card_token, subscription.price_in_cents)
      self.amount = self.subscription.price_in_cents
    end 

    def send_receipt
      Jackpot::Notifier.send_receipt(self).deliver
    end 

    def assign_public_token
      # Sets a public token so it can be accessed without being signed in
      self.public_token  ||= SecureRandom.hex(16)
    end 

    def customer_email
      customer.email  if customer.present?
    end 

    def amount
      amount_in_cents / 100 if amount_in_cents.present?
    end 

    def amount_in_cents
      read_attribute(:amount) 
    end 
  end
end

app/models/jackpot/subscription.rb
module Jackpot

  # Represents a subscription that is billed every month.
  class Subscription < ActiveRecord::Base
    has_many :customers
    has_many :payments

    validates_presence_of :name

    # Charge the subscriber the price of this subscription, using its saved credit card token
    def charge(customer_to_be_charged)
      payments.create(:customer => customer_to_be_charged)
    end 

    # Returns the price formatted in units
    def price
      (price_in_cents / 100.0) unless price_in_cents.nil?
    end 

    # Returns the raw price stored, in cents 
    def price_in_cents
      read_attribute(:price) 
    end 

  end
end

app/models/jackpot/user.rb
module Jackpot

  def self.table_name_prefix
    'jackpot_'
  end

  class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, 
           :registerable,
           :recoverable, 
           :rememberable, 
           :trackable, 
           :validatable, 
           :token_authenticatable

    # Setup accessible (or protected) attributes for your model
    attr_accessible :email, 
                    :password, 
                    :password_confirmation, 
                    :authentication_token, 
                    :remember_me
  end

end 

app/controllers/jackpot/application_controller.rb
module Jackpot
  class ApplicationController < ActionController::Base
  end
end

app/controllers/jackpot/customers_controller.rb
module Jackpot
  class CustomersController < ApplicationController
    before_filter :authenticate_user!

    # PUT /customers/37/credit_card 
    # Assigns a credit card to the given customer
    def credit_card 
      @customer = Customer.find           params[:id]
      @customer.update_credit_card        Card.new params[:credit_card]

      respond_to do |format|
        format.html { redirect_to @customer, 
                      notice: "This customer's card was successfully updated." } 
        format.json { head :ok }
      end 
    end 

    # GET /customers
    # GET /customers.json
    def index
      @customers = Customer.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @customers }
      end
    end

    # GET /customers/1
    # GET /customers/1.json
    def show
      @customer = Customer.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @customer }
      end
    end

    # GET /customers/new
    # GET /customers/new.json
    def new
      @customer = Customer.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @customer }
      end
    end

    # GET /customers/1/edit
    def edit
      @customer = Customer.find(params[:id])
    end

    # POST /customers
    # POST /customers.json
    def create
      @customer = Customer.new(params[:customer])

      respond_to do |format|
        if @customer.save
          format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
          format.json { render json: @customer, status: :created, location: @customer }
        else
          format.html { render action: "new" }
          format.json { render json: @customer.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /customers/1
    # PUT /customers/1.json
    def update
      @customer = Customer.find(params[:id])

      respond_to do |format|
        if @customer.update_attributes(params[:customer])
          format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @customer.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /customers/1
    # DELETE /customers/1.json
    def destroy
      @customer = Customer.find(params[:id])
      @customer.destroy

      respond_to do |format|
        format.html { redirect_to customers_url }
        format.json { head :ok }
      end
    end
  end
end

app/controllers/jackpot/payments_controller.rb
module Jackpot
  class PaymentsController < ApplicationController
    before_filter :authenticate_user!

    def create
      @customer = Jackpot::Customer.find params[:customer_id]

      respond_to do |format|
        if @customer.pay_subscription
          format.html { redirect_to(payments_url, notice: "Payment recorded successfully")}
        end
      end
    end

    def index
      @payments = Payment.all
    end
  end
end

app/controllers/jackpot/receipts_controller.rb
module Jackpot

  class ReceiptsController < ApplicationController
    before_filter :authenticate_user!, except: [ :public_show ]

    def show
      @payment = Payment.find params[:payment_id]
      render :pdf => 'receipt' 
    end 

    ## Shows a receipt using a public access token to display a receipt without authentication
    def public_show
      @payment = Payment.public_fetch params[:payment_id], :public_token => params[:public_token]
      render :pdf => 'receipt', :template => 'jackpot/receipts/show.pdf.erb'
    end 

  end 

end 

app/controllers/jackpot/subscriptions_controller.rb
module Jackpot
  class SubscriptionsController < ApplicationController
    before_filter :authenticate_user!
    # GET /subscriptions
    # GET /subscriptions.json
    def index
      @subscriptions = Subscription.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @subscriptions }
      end
    end
  
    # GET /subscriptions/1
    # GET /subscriptions/1.json
    def show
      @subscription = Subscription.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @subscription }
      end
    end
  
    # GET /subscriptions/new
    # GET /subscriptions/new.json
    def new
      @subscription = Subscription.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @subscription }
      end
    end
  
    # GET /subscriptions/1/edit
    def edit
      @subscription = Subscription.find(params[:id])
    end
  
    # POST /subscriptions
    # POST /subscriptions.json
    def create
      @subscription = Subscription.new(params[:subscription])
  
      respond_to do |format|
        if @subscription.save
          format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
          format.json { render json: @subscription, status: :created, location: @subscription }
        else
          format.html { render action: "new" }
          format.json { render json: @subscription.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /subscriptions/1
    # PUT /subscriptions/1.json
    def update
      @subscription = Subscription.find(params[:id])
  
      respond_to do |format|
        if @subscription.update_attributes(params[:subscription])
          format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @subscription.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /subscriptions/1
    # DELETE /subscriptions/1.json
    def destroy
      @subscription = Subscription.find(params[:id])
      @subscription.destroy
  
      respond_to do |format|
        format.html { redirect_to subscriptions_url }
        format.json { head :ok }
      end
    end
  end
end

app/helpers/jackpot/application_helper.rb
module Jackpot
  module ApplicationHelper
    def twitterized_type(type)
      case type
      when :alert
        "alert"
      when :error
        "alert alert-error"
      when :notice
        "alert alert-success"
      when :info
        "alert alert-info"
      else
        type.to_s
      end
    end

    def navbar_entry(name, options = {}, html_options = {}, &block)
      if current_page?(options) 
        content_tag("li", class: "active")  { link_to(name, options, html_options, &block) } 
      else
        content_tag("li")                   { link_to(name, options, html_options, &block) }
      end 
    end 


    def gravatar_for_current_user options = {}
      options = {:alt => 'avatar', :class => 'avatar', :size => 80}.merge! options
      id = Digest::MD5::hexdigest current_user.email.strip.downcase
      url = 'http://www.gravatar.com/avatar/' + id + '.jpg?s=' + options[:size].to_s
      options.delete :size
      image_tag url, options
    end

    def jackpot_gateway
      Jackpot.configuration.gateway["type"].to_s.humanize
    end 
    def jackpot_gateway_mode
      Jackpot.configuration.gateway["mode"].to_s.humanize
    end 

  end


end

app/helpers/jackpot/customers_helper.rb
module Jackpot
  module CustomersHelper
    def subscription_name_when_available(customer)
      (customer.subscription.present?) ? customer.subscription.name : "-" 
    end 
  end
end

app/helpers/jackpot/subscriptions_helper.rb
module Jackpot
  module SubscriptionsHelper
  end
end

app/views/jackpot/customers/_credit_card_form.html.erb
<%= form_tag(credit_card_customer_path, :method => :put , :id => "credit-card-form") do %>
  <fieldset>
    <legend>Credit Card Details</legend>


    <div class="optional text clearfix" id="credit_card_number">
      <%= label_tag      "credit_card[number]", "Number" %>
      <%= text_field_tag "credit_card[number]" %>
    </div>

    <div class="optional text clearfix" id="credit_card_month">
      <%= label_tag      "credit_card[month]", "Month" %>
      <%= text_field_tag "credit_card[month]" %>
    </div>

    <div class="optional text clearfix" id="credit_card_year">
      <%= label_tag      "credit_card[year]", "Year" %>
      <%= text_field_tag "credit_card[year]" %>
    </div>

    <div class="optional text clearfix" id="credit_card_first_name">
      <%= label_tag      "credit_card[first_name]", "First Name" %>
      <%= text_field_tag "credit_card[first_name]" %>
    </div>

    <div class="optional text clearfix" id="credit_card_last_name">
      <%= label_tag      "credit_card[last_name]", "Last Name" %>
      <%= text_field_tag "credit_card[last_name]" %>
    </div>

    <div class="optional text clearfix" id="credit_card_verification_value">
      <%= label_tag      "credit_card[verification_value]", 
                                      "Verification Value" %>
      <%= text_field_tag "credit_card[verification_value]" %>
    </div>

    <div class="actions">
      <%= submit_tag "Confirm" %>
    </div>

  </fieldset>
<% end %> 

app/views/jackpot/customers/_form.html.erb
<%= semantic_form_for @customer do |f| %>
  <%= f.semantic_errors %>

  <%= f.inputs do %>
    <%= f.input :email %>
    <%= f.input :description, :input_html => { 
      :class => 'autogrow', 
      :rows => 10, 
      :cols => 20, 
      :maxlength => 10  } %>
    <%= f.input :subscription %>
  <% end %>

  <%= f.buttons do %>
    <%= f.commit_button :button_html => { :class => "primary" } %> 
  <% end %> 
<% end %>

app/views/jackpot/customers/edit.html.erb
<h1> Editing customer </h1>

<div id="form-basic-information">

  <h2> Basic information </h2>
  <%= render 'form' %>
</div>

<div id="credit-card-information"> 
  <%= render 'credit_card_form' %>
</div>
<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/jackpot/customers/index.html.erb
<h1> Listing customers </h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Description</th>
      <th>Subscription</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <% @customers.each do |customer| %>
    <tr id="customer-<%= customer.id %>">
      <td><%= customer.email %> </td>
      <td><%= customer.description %> </td>
      <td><%= subscription_name_when_available(customer) %> </td>
      <td><%= link_to 'Show', customer %> </td>
      <td><%= link_to 'Edit', edit_customer_path(customer) %> </td>
      <td><%= link_to 'Destroy', customer, :confirm => 'Are you sure?', :method => :delete %> </td>
    </tr>
  <% end %>

</table>


<p>
  <%= link_to 'New Customer', new_customer_path %>
</p>

app/views/jackpot/customers/new.html.erb
<h1> New customer </h1>

<div id="form-basic-information">
  <h2> Basic information </h2>
  <%= render 'form' %>
</div>

<%= link_to 'Back', customers_path %>

app/views/jackpot/customers/show.html.erb
<p id="notice"> <%= notice %> </p>
<div id="customer">
  <p>
    <b> Email: </b> <%= @customer.email %>
  </p>

  <p>
    <b> Description: </b> <%= @customer.description %>
  </p>
  
  <p>
    <b> Subscription: </b> <%= @customer.subscription.name if @customer.subscription.present? %>
  </p>

  <h2> Billing information </h2>

  <% if @customer.credit_card_number.present? %>
    <p>
      <b> Credit Card Number: </b> <%= @customer.credit_card_number %>
    </p>
    <p>
      <b> Credit Card Expiration Date: </b> <%= @customer.expiration_date %>
    </p>
  <% else %>
    <p>
      There is no credit card information assigned to this customer yet 
    </p>
  <% end %> 
</div>

<%= link_to "Edit", edit_customer_path(@customer) %> | 
<%= link_to "Back", customers_path %>